engines:
  eslint:
    enabled: true
    checks:
      comma-dangle:
        enabled: false
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - "**.js"
exclude_paths:
  - tests/**
  - assets/tests/**
  - assets/vendor/**
