version: '2'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: nanocloud/backend:dev
    volumes:
      - ./:/opt/back
    env_file:
      - config.env
    network_mode: host
    container_name: "backend"

  frontend:
    build:
      context: ./assets
      dockerfile: Dockerfile-dev
    image: nanocloud/frontend:dev
    volumes:
      - ./assets:/opt
    network_mode: host
    container_name: "frontend"

  proxy:
    image: nanocloud/proxy
    volumes:
      - ./proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/certificates:/etc/nginx/ssl/:ro
    depends_on:
      - backend
    network_mode: host
    container_name: "proxy"
    restart: always
