version: '2'

services:
  storage-team:
    build: ./storage
    image: nanocloud/storage
    environment:
     - PLAZA_PORT=9091
    ports:
     - 445/udp:445/udp
     - 445:445
     - 9091:9091
    networks:
      - nanocloud
    depends_on:
      - plaza
    volumes:
      - plaza:/opt/plaza
    restart: always

  plaza:
    extends:
      file: docker-compose.yml
      service: plaza

networks:
  nanocloud:
    driver: bridge

volumes:
  plaza:
    driver: local
