version: '2'

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nanocloud/backend
    volumes:
      - static:/opt/back/assets/dist
    env_file:
      - config.env
    networks:
      - nanocloud
    restart: always

  frontend:
    build:
      context: ./assets
      dockerfile: Dockerfile
    image: nanocloud/frontend
    volumes:
      - static:/opt/dist
    networks:
      - nanocloud

  proxy:
    build: ./proxy
    image: nanocloud/proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    networks:
      - nanocloud
    restart: always

networks:
  nanocloud:
    driver: bridge

volumes:
  static:
    driver: local
